[project]
name = "yuriyomi-pagedetect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "numpy>=2.4.4",
    "onnxruntime>=1.28.0",
    "pillow>=12.2.0",
    "python-multipart>=0.0.32",
    "uvicorn>=0.52.1",
]

[project.optional-dependencies]
gpu = [
    "onnxruntime-gpu>=1.28.0",
]
